[versions]
kotlin="1.9.10"
agp="8.2.0-rc01"
compose="1.5.3"
activityCompose="1.7.2"
appcompat = "1.6.1"
coreKtx = "1.10.1"

[libraries]
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }


[plugins]

[bundles]