[versions]
android-minSdk = "24"
android-compileSdk = "34"
android-targetSdk = "34"
activityVersion = "1.8.0"
kotlin = "1.9.20"
agp = "8.2.0-rc02"
compose = "1.5.10"
activityCompose = "1.8.0"
appcompat = "1.6.1"
coreKtx = "1.12.0"
composeNavigationVersion = "2.7.4"
coilComposeVersion = "2.1.0"
dateTimeVersion = "0.4.0"
hiltVersion = "2.48.1"
hiltWorkVersion = "1.0.0"
workRuntimeKtxVersion = "2.8.1"
hiltCompilerVersion = "1.0.0"
ktorVersion = "2.3.0"
sqlDelightGradleVersion = "1.5.5"
sqlDelightVersion = "1.5.5"
## Tests
assertKVersion = "0.25"
turbineVersion = "0.7.0"
junit5 = "5.10.0"
junit4 = "4.13.2"
assertJ = "3.24.2"
mockito = "5.6.0"
testRunnerVersion = "1.5.2"
activity="1.8.0"

[libraries]
activity = { module = "androidx.activity:activity", version.ref = "activity" }
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
activity-v153 = { module = "androidx.activity:activity", version.ref = "activityVersion" }
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "compose" }
compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose" }
compose-animation = { module = "androidx.compose.animation:animation", version.ref = "compose" }
compose-runtime = { module = "androidx.compose.runtime:runtime", version.ref = "compose" }
compose-runtime-livedata = { module = "androidx.compose.runtime:runtime-livedata", version.ref = "compose" }
compose-runtime-rxjava3 = { module = "androidx.compose.runtime:runtime-rxjava3", version.ref = "compose" }
compose-material3-icons-core = { module = "androidx.compose.material3:material3-icons-core", version.ref = "compose" }
compose-material3-icons-extended = { module = "androidx.compose.material3:material3-icons-extended", version.ref = "compose" }
compose-navigation = { module = "androidx.navigation:navigation-compose", version.ref = "composeNavigationVersion" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coilComposeVersion" }
kotlin-dateTime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "dateTimeVersion" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hiltVersion" }
hilt-work = { module = "androidx.hilt:hilt-work", version.ref = "hiltWorkVersion" }
work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "workRuntimeKtxVersion" }
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hiltVersion" }
hilt-compiler = { module = "androidx.hilt:hilt-compiler", version.ref = "hiltCompilerVersion" }
hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltCompilerVersion" }
hilt-gradle-plugin = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "hiltVersion" }
ktor-core = { module = "io.ktor:ktor-client-core", version.ref = "ktorVersion" }
ktor-serialization = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktorVersion" }
ktor-serialization-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktorVersion" }
ktor-android = { module = "io.ktor:ktor-client-android", version.ref = "ktorVersion" }
ktor-ios = { module = "io.ktor:ktor-client-ios", version.ref = "ktorVersion" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
android-build-tool = { module = "com.android.tools.build:gradle", version.ref = "agp" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
sql-delight-gradle-plugin = { module = "com.squareup.sqldelight:gradle-plugin", version.ref = "sqlDelightGradleVersion" }
sql-delight-runtime = { module = "com.squareup.sqldelight:runtime", version.ref = "sqlDelightVersion" }
sql-delight-android-driver = { module = "com.squareup.sqldelight:android-driver", version.ref = "sqlDelightVersion" }
sql-delight-native-driver = { module = "com.squareup.sqldelight:native-driver", version.ref = "sqlDelightVersion" }
sql-delight-coroutines-extensions = { module = "com.squareup.sqldelight:coroutines-extensions", version.ref = "sqlDelightVersion" }

## Tests
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit5" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit5" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit5" }
assertj-core = { module = "org.assertj:assertj-core", version.ref = "assertJ" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockito" }
mockito-junit-jupiter = { module = "org.mockito:mockito-junit-jupiter", version.ref = "mockito" }
assert-ko = { module = "com.willowtreeapps.assertk:assertk", version.ref = "assertKVersion" }
turbine = { module = "app.cash.turbine:turbine", version.ref = "turbineVersion" }
junit4 = { module = "junit:junit", version.ref = "junit4" }
test-runner = { module = "androidx.test:runner", version.ref = "testRunnerVersion" }
compose-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "compose" }
compose-test-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "compose" }
hilt-testing = { module = "com.google.dagger:hilt-android-testing", version.ref = "hiltVersion" }

[plugins]
android-library = { id = "com.android.library", version.ref = "agp" }
android-application = { id = "com.android.application", version.ref = "agp" }
jetbrains-compose = { id = "org.jetbrains.compose", version.ref = "compose" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
dagger-hilt = { id = "com.google.dagger.hilt.android", version.ref = "hiltVersion" }
kotlin-plugin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
sqldelight = { id = "com.squareup.sqldelight", version.ref = "sqlDelightGradleVersion" }

[bundles]
test = [
    "junit-jupiter-api",
    "junit-jupiter-engine",
    "junit-jupiter",
    "assertj-core",
    "mockito-core",
    "mockito-junit-jupiter",
    "assert-ko",
    "turbine",
    "junit4",
    "test-runner",
    "compose-test-junit4",
    "compose-test-manifest",
    "hilt-testing"
]
hilt = [
    "hilt-android",
    "hilt-android-compiler",
    "hilt-compiler",
    "hilt-navigation-compose"
#    "hilt-gradle-plugin"
]
compose = [
    "compose-ui",
    "compose-ui-tooling",
    "compose-ui-tooling-preview",
    "compose-material3",
    "compose-foundation",
    "compose-animation",
    "compose-runtime",
    "compose-runtime-livedata",
    "compose-runtime-rxjava3",
    "compose-material3-icons-core",
    "compose-material3-icons-extended",
    "compose-navigation",
    "coil-compose"
]
ktor = [
    "ktor-core",
    "ktor-serialization",
    "ktor-serialization-json"
]
sql-delight = [
    "sql-delight-runtime",
    "sql-delight-coroutines-extensions"
]
