@file:Suppress("unused")

package com.ideabaker.kmp.translator.core.presentation.theme

import androidx.compose.ui.graphics.Color

object BlueColorTheme: ColorTheme {
  override val md_theme_light_primary = Color(0xFF5A48CE)
  override val md_theme_light_onPrimary = Color(0xFFFFFFFF)
  override val md_theme_light_primaryContainer = Color(0xFFE4DFFF)
  override val md_theme_light_onPrimaryContainer = Color(0xFF180065)
  override val md_theme_light_secondary = Color(0xFF5F5C71)
  override val md_theme_light_onSecondary = Color(0xFFFFFFFF)
  override val md_theme_light_secondaryContainer = Color(0xFFE5DFF9)
  override val md_theme_light_onSecondaryContainer = Color(0xFF1B192C)
  override val md_theme_light_tertiary = Color(0xFF7B5265)
  override val md_theme_light_onTertiary = Color(0xFFFFFFFF)
  override val md_theme_light_tertiaryContainer = Color(0xFFFFD8E7)
  override val md_theme_light_onTertiaryContainer = Color(0xFF301121)
  override val md_theme_light_error = Color(0xFFBA1A1A)
  override val md_theme_light_errorContainer = Color(0xFFFFDAD6)
  override val md_theme_light_onError = Color(0xFFFFFFFF)
  override val md_theme_light_onErrorContainer = Color(0xFF410002)
  override val md_theme_light_background = Color(0xFFFFFBFF)
  override val md_theme_light_onBackground = Color(0xFF1C1B1F)
  override val md_theme_light_surface = Color(0xFFFFFBFF)
  override val md_theme_light_onSurface = Color(0xFF1C1B1F)
  override val md_theme_light_surfaceVariant = Color(0xFFE5E1EC)
  override val md_theme_light_onSurfaceVariant = Color(0xFF47464F)
  override val md_theme_light_outline = Color(0xFF78767F)
  override val md_theme_light_inverseOnSurface = Color(0xFFF4EFF4)
  override val md_theme_light_inverseSurface = Color(0xFF313034)
  override val md_theme_light_inversePrimary = Color(0xFFC7BFFF)
  override val md_theme_light_shadow = Color(0xFF000000)
  override val md_theme_light_surfaceTint = Color(0xFF5A48CE)
  override val md_theme_light_outlineVariant = Color(0xFFC9C5D0)
  override val md_theme_light_scrim = Color(0xFF000000)

  override val md_theme_dark_primary = Color(0xFFC7BFFF)
  override val md_theme_dark_onPrimary = Color(0xFF2A009F)
  override val md_theme_dark_primaryContainer = Color(0xFF422BB5)
  override val md_theme_dark_onPrimaryContainer = Color(0xFFE4DFFF)
  override val md_theme_dark_secondary = Color(0xFFC8C3DC)
  override val md_theme_dark_onSecondary = Color(0xFF302E41)
  override val md_theme_dark_secondaryContainer = Color(0xFF474459)
  override val md_theme_dark_onSecondaryContainer = Color(0xFFE5DFF9)
  override val md_theme_dark_tertiary = Color(0xFFECB8CE)
  override val md_theme_dark_onTertiary = Color(0xFF482537)
  override val md_theme_dark_tertiaryContainer = Color(0xFF613B4D)
  override val md_theme_dark_onTertiaryContainer = Color(0xFFFFD8E7)
  override val md_theme_dark_error = Color(0xFFFFB4AB)
  override val md_theme_dark_errorContainer = Color(0xFF93000A)
  override val md_theme_dark_onError = Color(0xFF690005)
  override val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
  override val md_theme_dark_background = Color(0xFF1C1B1F)
  override val md_theme_dark_onBackground = Color(0xFFE5E1E6)
  override val md_theme_dark_surface = Color(0xFF1C1B1F)
  override val md_theme_dark_onSurface = Color(0xFFE5E1E6)
  override val md_theme_dark_surfaceVariant = Color(0xFF47464F)
  override val md_theme_dark_onSurfaceVariant = Color(0xFFC9C5D0)
  override val md_theme_dark_outline = Color(0xFF928F99)
  override val md_theme_dark_inverseOnSurface = Color(0xFF1C1B1F)
  override val md_theme_dark_inverseSurface = Color(0xFFE5E1E6)
  override val md_theme_dark_inversePrimary = Color(0xFF5A48CE)
  override val md_theme_dark_shadow = Color(0xFF000000)
  override val md_theme_dark_surfaceTint = Color(0xFFC7BFFF)
  override val md_theme_dark_outlineVariant = Color(0xFF47464F)
  override val md_theme_dark_scrim = Color(0xFF000000)

  val LightBlue = Color(0xFFA8A5BB)
  val LightBlueGrey = Color(0xFFF6F4F4)
  val AccentViolet = Color(0xFF5643C9)
  val TextBlack = Color(0xFF111111)
  val DarkGrey = Color(0xFF282C31)

  override val seed = Color(0xFF5643C9)
}

