@file:Suppress("unused")

package com.ideabaker.kmp.translator.core.presentation.theme
import androidx.compose.ui.graphics.Color

object GreenColorTheme: ColorTheme {
  override val md_theme_light_primary = Color(0xFF456812)
  override val md_theme_light_onPrimary = Color(0xFFFFFFFF)
  override val md_theme_light_primaryContainer = Color(0xFFC5F08B)
  override val md_theme_light_onPrimaryContainer = Color(0xFF102000)
  override val md_theme_light_secondary = Color(0xFF586249)
  override val md_theme_light_onSecondary = Color(0xFFFFFFFF)
  override val md_theme_light_secondaryContainer = Color(0xFFDCE7C7)
  override val md_theme_light_onSecondaryContainer = Color(0xFF161E0B)
  override val md_theme_light_tertiary = Color(0xFF386662)
  override val md_theme_light_onTertiary = Color(0xFFFFFFFF)
  override val md_theme_light_tertiaryContainer = Color(0xFFBCECE7)
  override val md_theme_light_onTertiaryContainer = Color(0xFF00201E)
  override val md_theme_light_error = Color(0xFFBA1A1A)
  override val md_theme_light_errorContainer = Color(0xFFFFDAD6)
  override val md_theme_light_onError = Color(0xFFFFFFFF)
  override val md_theme_light_onErrorContainer = Color(0xFF410002)
  override val md_theme_light_background = Color(0xFFFDFCF5)
  override val md_theme_light_onBackground = Color(0xFF1B1C18)
  override val md_theme_light_surface = Color(0xFFFDFCF5)
  override val md_theme_light_onSurface = Color(0xFF1B1C18)
  override val md_theme_light_surfaceVariant = Color(0xFFE1E4D5)
  override val md_theme_light_onSurfaceVariant = Color(0xFF44483D)
  override val md_theme_light_outline = Color(0xFF75796C)
  override val md_theme_light_inverseOnSurface = Color(0xFFF2F1E9)
  override val md_theme_light_inverseSurface = Color(0xFF30312C)
  override val md_theme_light_inversePrimary = Color(0xFFAAD472)
  override val md_theme_light_shadow = Color(0xFF000000)
  override val md_theme_light_surfaceTint = Color(0xFF456812)
  override val md_theme_light_outlineVariant = Color(0xFFC5C8B9)
  override val md_theme_light_scrim = Color(0xFF000000)

  override val md_theme_dark_primary = Color(0xFFAAD472)
  override val md_theme_dark_onPrimary = Color(0xFF203700)
  override val md_theme_dark_primaryContainer = Color(0xFF304F00)
  override val md_theme_dark_onPrimaryContainer = Color(0xFFC5F08B)
  override val md_theme_dark_secondary = Color(0xFFC0CBAC)
  override val md_theme_dark_onSecondary = Color(0xFF2A331E)
  override val md_theme_dark_secondaryContainer = Color(0xFF404A33)
  override val md_theme_dark_onSecondaryContainer = Color(0xFFDCE7C7)
  override val md_theme_dark_tertiary = Color(0xFFA0D0CB)
  override val md_theme_dark_onTertiary = Color(0xFF003734)
  override val md_theme_dark_tertiaryContainer = Color(0xFF1F4E4B)
  override val md_theme_dark_onTertiaryContainer = Color(0xFFBCECE7)
  override val md_theme_dark_error = Color(0xFFFFB4AB)
  override val md_theme_dark_errorContainer = Color(0xFF93000A)
  override val md_theme_dark_onError = Color(0xFF690005)
  override val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
  override val md_theme_dark_background = Color(0xFF1B1C18)
  override val md_theme_dark_onBackground = Color(0xFFE3E3DB)
  override val md_theme_dark_surface = Color(0xFF1B1C18)
  override val md_theme_dark_onSurface = Color(0xFFE3E3DB)
  override val md_theme_dark_surfaceVariant = Color(0xFF44483D)
  override val md_theme_dark_onSurfaceVariant = Color(0xFFC5C8B9)
  override val md_theme_dark_outline = Color(0xFF8F9285)
  override val md_theme_dark_inverseOnSurface = Color(0xFF1B1C18)
  override val md_theme_dark_inverseSurface = Color(0xFFE3E3DB)
  override val md_theme_dark_inversePrimary = Color(0xFF456812)
  override val md_theme_dark_shadow = Color(0xFF000000)
  override val md_theme_dark_surfaceTint = Color(0xFFAAD472)
  override val md_theme_dark_outlineVariant = Color(0xFF44483D)
  override val md_theme_dark_scrim = Color(0xFF000000)

  override val seed = Color(0xFF456813)
}
